### ISSUE TITLE
Allow choosing a range of fares in the colour picker

### ISSUE THREAD

**Issue by willfurnell** [JakeCracknell/fare_map#4]
Hi,
Would it be possible to be able to choose a range of fares in the colour picker please? Or just be able to click on the colour picker to set the current price point? Then I would be able to see all the stations I could get to for £40 (or any number) for example - as the map colouring disappears as soon as I stop hovering on the colour picker?

Thanks,

Will.

**Comment by JakeCracknell** [comment]
Hi Will,
I'll be looking at this today. ATOC recently uploaded the latest fare data so would be looking to update that as well.
It might take a while to get it all uploaded, but I will close the issue when it is done. It shouldn't take too long to implement.
Best,
Jake

**Comment by JakeCracknell** [comment]
Should all be done now - you might need to Ctrl+F5 the first time to get it to work. The max price is locked when clicking on the color picker. It unlocks when you click it again or change the source station. It also unlocks when panning around the map, but it would be difficult to change this behaviour due to the way it is all designed. Hopefully the current implementation meets your use case :)

**Comment by willfurnell** [comment]
All looks good to me, thank you very much!
